theme: jekyll-theme-minimal
title: Valentine Danilov
description: Valentine Danilov - software engineer with 2 year of experience in e-commerce domain and 4 years expereince in Java languge.
logo: /me.jpg
